name: 'Deploy to AWS CloudFormation'
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIA5T4R6ZW3STMOTJI6
          aws-secret-access-key: x413HjUb+z4ml1FO7OfBpE2cc/LQOvSw0/CVLeMH
          aws-session-token: FwoGZXIvYXdzEC4aDCaKC7zMrbNmcepIrSLFAbnBa5ox3BQtrF85NIuQr1JsQMvrQ9TenHLy6rnDwFtcDy6Lx99iaGrg/jSMwC1h9l4IBIWr+5/CoZQMOA7fYKAXqpn4PjqeQoh9HdDGYUv47/SOLR/keCBxJxsozJVyttlktDdBV+5/QY8q7JBkm0E13v3hzRzL1HxPFy/03+CWOqVK3srfj1EeBbZ3eGmvdsxuLO/qtG6bIJ1c/sOVLI4s+qZ60sCyM0YrDD0ICMgreLUkMtPHNTadOsqinbjXCH4G8rM1KOHv+aAGMi12EDFuIA7+/0LPfgZv5vxWRoVyVzutwZJLOpXT0xgrSPbuC4Y7ccpqh1C54OQ=
          aws-region: 'us-east-1' 

      # Deploy to AWS CloudFormation
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: test-stack
          template: Final-CFT.yml
          no-fail-on-empty-changeset: "1"
          
